#!/usr/bin/env bash
# Only use ssh single-character flags
# You cannot use -l
# You do not need to handle the case of a private key protected by a passphrase
ssh -i ~/.ssh/id_rsa ubuntu@107.23.22.152
